### ISSUE TITLE
Please provide the latest version of the library?

### ISSUE THREAD

**Issue by ravindra0821** [pgreze/android-reactions#13]
Hello sir, Please provide me the latest version of the library, i have searched all around but not getting the version of the library,please help me on it..Thanks

**Comment by pgreze** [comment]
@ravindra0821 hey! Hope you could find the latest version.
Latest version is 1.2.1 that I just pushed today.

I moved the jcenter badge in the installation title, so hopefully it will be easier to discover 👍
