### ISSUE TITLE
Enable jacoco / codecov

### ISSUE THREAD

**Issue by pgreze** [pgreze/android-reactions#20]
Not as easy as a standard Kotlin build due to default jacoco not supporting Android :(

**Comment by Marchuck** [comment]
what about 
http://vgaidarji.me/blog/2017/12/20/how-to-configure-jacoco-for-kotlin-and-java-project/
or
https://andrey-fomenkov.medium.com/kotlin-jacoco-tuning-compiler-to-skip-generated-code-935fcaeaa391

**Comment by pgreze** [comment]
With recent news about codecov, I'm actually happy I didn't integrate it so far, and not sure it's worth the risk...
