### ISSUE TITLE
popup always centered horizontally

### ISSUE THREAD

**Issue by ChaosWizard99** [pgreze/android-reactions#5]
Is there any way to change the X position of the popup? or the gravity of it?

something like this(it is photoshop btw):

![wasd](https://user-images.githubusercontent.com/35845968/62424838-1ed4eb80-b69a-11e9-811b-5d0663f07711.jpg)

**Comment by pgreze** [comment]
Hi, happy you found this library useful for your project.

With a FAB on right of the screen, fallback position is always centered:
https://github.com/pgreze/android-reactions/blob/5ee4b04fcb2cdbb41615a6db1fa98144f86c16e9/library/src/main/java/com/github/pgreze/reactions/ReactionViewGroup.kt#L127

Let me try to add an optional gravity parameter during setup to avoid this fallback.

**Comment by ChaosWizard99** [comment]
will you realease a new version with that?

**Comment by pgreze** [comment]
Try this new version and let me know if it's fitting your need:
https://bintray.com/pgreze/maven/android-reactions/1.1

**Comment by ChaosWizard99** [comment]
Yes, thats pretty nice, and it also has more options,  Thank you!
