### ISSUE TITLE
Need to release hold to navigate through PopupWindow in RecyclerView

### ISSUE THREAD

**Issue by Baaaaatz** [pgreze/android-reactions#6]
Whenever PopupWindow shows, i need to release my hold so i can navigate trough na popupwindow. Is there a workaround for this? Thank you

**Comment by pgreze** [comment]
Could you provide some sample code?
Also sample app is providing several ways to use the library, could you confirm your code is acting similarly than sample code?

**Comment by Pro-55** [comment]
`img_btn_reaction.setOnTouchListener(getReactionPopup(context).apply {
                reactionSelectedListener = { position ->
                    isPopupShowing = false
                    val reactionType = if (position > -1) position + 1 else position
                    Log.d("TAG", "TestLog: rT:$reactionType")
                    true
                }
            })`

This is how i am using is in the recyclerview adapter. I am facing similar issue where pop up is not shown half of the time & if it is shown then i have to re-position my finger up to select a reaction
